import 'package:tarea_2/util/app_string.dart';

const Map<Strings, String> dictionaryEn = {
  Strings.bienvenidaString: "Welcome back",
  Strings.bienvenida2String: "we miss you! Login to start",
  Strings.loginString: "Login",
  Strings.passwordString: "Password",
  Strings.emailString: "Email",
  Strings.rememberString: "Remember me",
  Strings.acountString: "Don't have an account?",
  Strings.helpString: "Need help?",
  Strings.registrateString: "Register",
  Strings.signInString: "Sign In",
  Strings.clientesString: "Customers",
  Strings.segurosString: "Insurance",
  Strings.siniestrosString: "Sinisters",
  Strings.tablaModificableString: "Modifiable table",
  Strings.cerrarSesionString: "Close Session",
  Strings.forzarCerrarSesionString: "Force Logout",
  Strings.nombreString: "Name",
  Strings.apellidoString: "First Surname",
  Strings.apellido2String: "Second Surname",
  Strings.telefonoString: "Phone",
  Strings.viaString: "Via",
  Strings.claseViaString: "Via Class",
  Strings.numeroViaString: "No. Via",
  Strings.postalString: "Postcard",
  Strings.ciudadString: "City",
  Strings.observacionesString: "Remarks",
  Strings.numeroPolizaString: "Policy Number",
  Strings.dniClienteString: "Customer ID",
  Strings.ramoString: "Bouquet",
  Strings.condicionesString: "Special conditions",
  Strings.fechaInicioString: "Start Date",
  Strings.fechaFinString: "End Date",
  Strings.registroClienteString: "Register Customer",
  Strings.registroSeguroString: "Register Insurance",
  Strings.registroSiniestroString: "Register Sinister",
  Strings.idSiniestroString: "Sinister Id",
  Strings.indermizacionString: "Indermization",
  Strings.causasString: "Causes",
  Strings.aceptadoString: "Accepted",
  Strings.fechaSiniestroString: "Date of Sinister",
  Strings.dniPeritoString: "DNI Perito",
  Strings.actualizadoSiniestroString: "DNI Expert",
  Strings.eliminadoSiniestroString: "Sinister successfully eliminated",
  Strings.guardadoSiniestroString: "Sinister creado con exito",
  Strings.errorEliminarSiniestroString: "Error when deleting the Sinister",
  Strings.errorActualizarSiniestroString: "Error updating the Sinister",
  Strings.errorRegistrarSiniestroString: "Error creating the Sinister",
  Strings.mensajeEliminarSiniestro:
      "Are you sure to delete the selected Sinister with ID:",
  Strings.cancelarString: "Cancel",
  Strings.errorEmailString: "The indicated email does not exist",
  Strings.errorPasswordString: "Incorrect password",
  Strings.offlineString: "No internet connection",
  Strings.actualizadoSeguroString: "Insurance successfully updated",
  Strings.eliminadoSeguroString: "Insurance successfully eliminated",
  Strings.guardadoSeguroString: "Insurance successfully created",
  Strings.errorEliminarSeguroString: "Error deleting Insurance",
  Strings.errorActualizarSeguroString: "Error updating insurance",
  Strings.errorRegistrarSeguroString: "Error when creating insurance",
  Strings.mensajeEliminarSeguro:
      "Are you sure to delete the selected insurance with Policy Number:",
  Strings.actualizadoClienteString: "Customer successfully upgraded",
  Strings.eliminadoClienteString: "Customer successfully removed",
  Strings.guardadoClienteString: "Customer successfully created",
  Strings.errorEliminarClienteString: "Error deleting Client",
  Strings.errorActualizarClienteString: "Error updating the Client",
  Strings.errorRegistrarClienteString: "Error when creating the Client",
  Strings.mensajeEliminarCliente:
      "Are you sure to delete the selected customer with DNI:",
  Strings.errorEmailForm: "Please enter an email",
  Strings.errorEmailForm2: "Please enter a valid Email",
  Strings.errorPasswordForm: "Please enter your Password",
  Strings.guardarString: "Save",
  Strings.errorNameForm: "Please enter your Name",
  Strings.errorApelidoForm: "Please enter your First Surname",
  Strings.errorApelido2Form: "Please enter your Second Surname",
  Strings.errorTelefonoForm: "Please enter your Phone",
  Strings.errorTelefonoForm2: "Please enter a valid Phone",
  Strings.errorViaForm: "Please enter your Via",
  Strings.errorClaseViaForm: "Please enter your Via Class",
  Strings.errorNumeroViaForm: "Please enter your No. Via",
  Strings.errorPostalForm: "Please enter your Postcard",
  Strings.errorPostalForm2: "Please enter a valid Postcard",
  Strings.errorCiudadForm: "Please enter your City",
  Strings.errorObservacionesForm: "Please enter your Remarks",
  Strings.errorNumeroPolizaForm: "Please enter your Policy Number",
  Strings.errorDniClienteForm: "Please enter your Customer ID",
  Strings.errorRamoForm: "Please enter your Bouquet",
  Strings.errorCondicionesForm: "Please enter your Special conditions",
  Strings.errorFechaInicioForm: "Please enter your Start Date",
  Strings.errorFechaFinForm: "Please enter your End Date",
  Strings.errorIdSiniestroForm: "Please enter your Sinister Id",
  Strings.errorIndermizacionForm: "Please enter your Indermization",
  Strings.errorCausasForm: "Please enter your Causes",
  Strings.errorAceptadoForm: "Please enter your Accepted",
  Strings.errorFechaSiniestroForm: "Please enter your Date of Sinister",
  Strings.errorDniPeritoForm: "Please enter your DNI Perito",
  Strings.perfilString: "Profile",
  Strings.signInTitleString: "Stored session",
  Strings.cancelButtonString: "Cancel",
  Strings.goToSettingsButtonString: "Settings",
  Strings.biometricHintString: "Put your finger on the sensor",
  Strings.biometricNotRecognizedString: "unrecognized fingerprint",
  Strings.biometricSuccessString: "Recognized footprint",
  Strings.goToSettingsDescriptionString: "Please set your fingerprint",
  Strings.localizedReasonString: "Authenticate to access",
  Strings.lockedOutString: "API temporarily blocked due to too many attempts",
  Strings.notAvailableString:
      "The device does not have hardware support for biometric data",
  Strings.notEnrolledString: "No biometric data is found on the device",
  Strings.otherOperatingSystemString:
      "Operating system not compatible with biometric data",
  Strings.passcodeNotSetString: "No access code found on the device",
  Strings.permanentlyLockedOutString:
      "API permanently blocked due to too many attempts, enter your security pin or pattern",
};
