import 'package:tarea_2/util/app_string.dart';

const Map<Strings, String> dictionaryEs = {
  Strings.bienvenidaString: "Bienvenido de nuevo",
  Strings.bienvenida2String: "!te extrañamos! Inicie sesión para comenzar",
  Strings.loginString: "Iniciar sesión",
  Strings.passwordString: "Contraseña",
  Strings.emailString: "Correo Electronico",
  Strings.rememberString: "Recordarme",
  Strings.acountString: "¿No tienes cuenta?",
  Strings.helpString: "¿Necesitas ayuda?",
  Strings.registrateString: "Registrate",
  Strings.signInString: "Iniciar Sesión",
  Strings.clientesString: "Clientes",
  Strings.segurosString: "Seguros",
  Strings.siniestrosString: "Siniestros",
  Strings.tablaModificableString: "Tabla modificable",
  Strings.cerrarSesionString: "Cerrar Sesión",
  Strings.forzarCerrarSesionString: "Forzar Cierre de Sesión",
  Strings.nombreString: "Nombre",
  Strings.apellidoString: "Primer Apellido",
  Strings.apellido2String: "Segundo Apellido",
  Strings.telefonoString: "Telefono",
  Strings.viaString: "Via",
  Strings.claseViaString: "Clase de Via",
  Strings.numeroViaString: "No. Via",
  Strings.postalString: "Postal",
  Strings.ciudadString: "Ciudad",
  Strings.observacionesString: "Observaciones",
  Strings.numeroPolizaString: "Numero de Poliza",
  Strings.dniClienteString: "DNI Cliente",
  Strings.ramoString: "Ramo",
  Strings.condicionesString: "Condiciones particulares",
  Strings.fechaInicioString: "Fecha de Inicio",
  Strings.fechaFinString: "Fecha de Fin",
  Strings.registroClienteString: "Registrar Cliente",
  Strings.registroSeguroString: "Registrar Seguro",
  Strings.registroSiniestroString: "Registrar Siniestro",
  Strings.idSiniestroString: "Id Siniestro",
  Strings.indermizacionString: "Indermización",
  Strings.causasString: "Causas",
  Strings.aceptadoString: "Aceptado",
  Strings.fechaSiniestroString: "Fecha del Siniestro",
  Strings.dniPeritoString: "DNI Perito",
  Strings.actualizadoSiniestroString: "Siniestro actualizado con exito",
  Strings.eliminadoSiniestroString: "Siniestro eliminado con exito",
  Strings.guardadoSiniestroString: "Siniestro creado con exito",
  Strings.errorEliminarSiniestroString: "Error al eliminar el siniestro",
  Strings.errorActualizarSiniestroString: "Error al actualizar el siniestro",
  Strings.errorRegistrarSiniestroString: "Error al crear el siniestro",
  Strings.mensajeEliminarSiniestro:
      "¿Esta seguro de eliminar el siniestro seleccionado con ID:",
  Strings.cancelarString: "Cancelar",
  Strings.errorEmailString: "El email indicado no existe",
  Strings.errorPasswordString: "Contraseña incorrecta",
  Strings.offlineString: "No hay conexión a internet",
  Strings.actualizadoSeguroString: "Seguro actualizado con exito",
  Strings.eliminadoSeguroString: "Seguro eliminado con exito",
  Strings.guardadoSeguroString: "Seguro creado con exito",
  Strings.errorEliminarSeguroString: "Error al eliminar el Seguro",
  Strings.errorActualizarSeguroString: "Error al actualizar el Seguro",
  Strings.errorRegistrarSeguroString: "Error al crear el Seguro",
  Strings.mensajeEliminarSeguro:
      "¿Esta seguro de eliminar el seguro seleccionado con Numero de Poliza:",
  Strings.actualizadoClienteString: "Cliente actualizado con exito",
  Strings.eliminadoClienteString: "Cliente eliminado con exito",
  Strings.guardadoClienteString: "Cliente creado con exito",
  Strings.errorEliminarClienteString: "Error al eliminar el Cliente",
  Strings.errorActualizarClienteString: "Error al actualizar el Cliente",
  Strings.errorRegistrarClienteString: "Error al crear el Cliente",
  Strings.mensajeEliminarCliente:
      "¿Esta seguro de eliminar el cliente seleccionado con DNI:",
  Strings.errorEmailForm: "Por favor, introduzca un Email",
  Strings.errorEmailForm2: "Por favor, introduzca un Email valido",
  Strings.errorPasswordForm: "Por favor, introduzca su Password",
  Strings.guardarString: "Guardar",
  Strings.errorNameForm: "Por favor, introduzca su Nombre",
  Strings.errorApelidoForm: "Por favor, introduzca su Primer Apellido",
  Strings.errorApelido2Form: "Por favor, introduzca su Segundo Apellido",
  Strings.errorTelefonoForm: "Por favor, introduzca su Telefono",
  Strings.errorTelefonoForm2: "Por favor, introduzca un Telefono valido",
  Strings.errorViaForm: "Por favor, introduzca su Via",
  Strings.errorClaseViaForm: "Por favor, introduzca su Clase de Via",
  Strings.errorNumeroViaForm: "Por favor, introduzca su Numero de Via",
  Strings.errorPostalForm: "Por favor, introduzca su Postal",
  Strings.errorPostalForm2: "Por favor, introduzca un Postal valido",
  Strings.errorCiudadForm: "Por favor, introduzca su Ciudad",
  Strings.errorObservacionesForm: "Por favor, introduzca sus Observaciones",
  Strings.errorNumeroPolizaForm: "Por favor, introduzca su Numero de Poliza",
  Strings.errorDniClienteForm: "Por favor, introduzca su DNI",
  Strings.errorRamoForm: "Por favor, introduzca su Ramo",
  Strings.errorCondicionesForm:
      "Por favor, introduzca sus Condiciones particulares",
  Strings.errorFechaInicioForm: "Por favor, introduzca su Fecha de Inicio",
  Strings.errorFechaFinForm: "Por favor, introduzca su Fecha de Fin",
  Strings.errorIdSiniestroForm: "Por favor, introduzca su Id de Siniestro",
  Strings.errorIndermizacionForm: "Por favor, introduzca su Indermizacion",
  Strings.errorCausasForm: "Por favor, introduzca sus Causas",
  Strings.errorAceptadoForm: "Por favor, introduzca su Aceptado",
  Strings.errorFechaSiniestroForm:
      "Por favor, introduzca su Fecha de Siniestro",
  Strings.errorDniPeritoForm: "Por favor, introduzca su DNI de Perito",
  Strings.perfilString: "Perfil",
  Strings.signInTitleString: "Sesión Almacenada",
  Strings.cancelButtonString: "Cancelar",
  Strings.goToSettingsButtonString: "Ajustes",
  Strings.biometricHintString: "Pon el dedo en el sensor",
  Strings.biometricNotRecognizedString: "Huella no reconocida",
  Strings.biometricSuccessString: "Huella reconocida",
  Strings.goToSettingsDescriptionString: "Por favor configure su huella",
  Strings.localizedReasonString: "Autentiquese para acceder",
  Strings.lockedOutString:
      "API bloqueada temporalmente debido a demasiados intentos",
  Strings.notAvailableString:
      "El dispositivo no tiene soporte de hardware para datos biometricos",
  Strings.notEnrolledString:
      "No se encuentra ningun dato biometrico en el dispositivo",
  Strings.otherOperatingSystemString:
      "Sistema operativo no compatible con datos biometricos",
  Strings.passcodeNotSetString:
      "No se encuentra ningun codigo de acceso en el dispositivo",
  Strings.permanentlyLockedOutString:
      "API bloqueada permanentemente debido a demasiados intentos, coloque su pin o patron de seguridad",
};
